# Generated by Django 2.1.1 on 2018-10-04 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ANIMAL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_scientifique', models.CharField(max_length=100, unique=True)),
                ('nom_commun', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CLASSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAMILLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famille', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ORDRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifap.CLASSE'),
        ),
        migrations.AddField(
            model_name='animal',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifap.FAMILLE'),
        ),
        migrations.AddField(
            model_name='animal',
            name='ordre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifap.ORDRE'),
        ),
    ]
